### ISSUE TITLE
cowboy dependancy possibly needs updating?

### ISSUE THREAD

**Issue by 9Dave9** [mneudert/plug_accesslog#13]
Add plug_accesslog to list of deps in mix.exs file and I get the below?

```
kinde $ mix deps.get
Resolving Hex dependencies...

Failed to use "cowboy" because
  plug_accesslog (version 0.14.0) requires ~> 1.0
  plug_cowboy (version 2.1.2) requires ~> 2.5
  mix.lock specifies 2.7.0
```

I guess it's a really old dependancy?

**Comment by 9Dave9** [comment]
PR https://github.com/mneudert/plug_accesslog/pull/14 attempts to rectify dependency issues for supporting later versions of plug_cowboy(currently on 2.0) and in turn later versions of cowboy(currently 2.8.0).

**Comment by mneudert** [comment]
Could you also as an alternative try to add a dependency override to your project's `mix.exs` file?

```elixir
def deps do
  [
    # ...
    {:cowboy, "~> 2.5", override: true}
    # ...
  ]
end
```

As the last release of this library is nearly 4 years old there is probably more to update to get it to a really usable state again. For example the dependency on `:timex` should be easily replaced with a native `DateTime` value 🤔

**Comment by 9Dave9** [comment]
I can't  - as the `override` option drops to a much lower major version of `cowboy` which doesn't make me feel very comfortable as I have other dependancies relying on a version much higher than `1.0`.

Updating `cowboy` seemed to do the trick for myself. I'm using an ubuntu based docker image so had to add tzdata package to my build because of `:timex` - so you're right - probably could do with an update. But this works like a charm for me now haha.

I might take a look at replacing `:timex` with `DateTime` this weekend if I am able find a bit of time though.

**Comment by mneudert** [comment]
Took long enough but I have released a fixed version that should no longer warn when using with recent versions of `:phoenix` or a plain `:plug_cowboy` :)
