### ISSUE TITLE
Problem: Request headers are not logged correctly

### ISSUE THREAD

**Issue by c-rack** [mneudert/plug_accesslog#2]
Using the `:combined_vhost` format produces always `-` for `Referer` and `User-Agent` headers, because request headers must be accessed with all characters lowercase. Otherwise they are not found.

**Comment by mneudert** [comment]
Hm, I think I messed that one up :D

I will have a complete fix (including tests ^^) later up as v0.5.1 on Hex. That should also include accessing the Response-Headers (like "%{Content-Length}o") as v0.12.3-dev of Plug raises if they are not lowercase.

**Comment by mneudert** [comment]
Using both the current master and the release v0.5.1 should fix that issue.

Thank you for finding and reporting (and fixing) it :+1:

**Comment by c-rack** [comment]
That was fast, thanks!
