### ISSUE TITLE
erlang error: terminated

### ISSUE THREAD

**Issue by houshuang** [mneudert/plug_accesslog#5]
I find several entries like this in my log:

``` elixir
info] Sent 500 in 83ms
[error] #PID<0.590.0> running Survey.Endpoint terminated
Server: localhost:8000 (http)
Request: GET /admin/chat?password=test
** (exit) an exception was raised:
    ** (ErlangError) erlang error: :terminated
        (stdlib) :io.put_chars(#PID<0.592.0>, :unicode, "127.0.0.1 - - [02/Jul/2015:22:16:20 +0800] \"GET /admin/chat HTTP/1.1\" 200 869\n")
        (plug_accesslog) lib/plug/accesslog.ex:53: Plug.AccessLog.maybe_log/3
        (elixir) lib/enum.ex:1261: Enum."-reduce/3-lists^foldl/2-0-"/3
```

Initially I thought maybe it happened if the logger was writing just as I restarted the app, but currently I was just doing some development, and it happened again. Don't know what this means or how to debug it, it's making me quite nervous.

**Comment by mneudert** [comment]
Probably the IO device to the logfile had a problem. Could anything have happened to the logfile? Like it being deleted and recreated outside of the Plug?

At the moment the file will be recreated if it is not already existing. Having a fault inside the IO process of the openened logfile may cause some weird behaviour that is not properly handled...

**Comment by houshuang** [comment]
Sounds weird. This last case was actually two web browser windows pointing
at the same URL, and they both reloaded at the same time (I'm playing with
channels). The first one was fine, the second one crashed because of the
logger issue. My greater issue here though is that the whole request
crashed - I don't mind loosing a log entry, but it should definitively be
isolated such that no matter what happens with the logger, the request is
completed. I had to remove accesslog from production until I figure out
what this is. Had this happen about 10 times in my logs in 24 hours.

Happy to help debug if you know where I should look.

Stian

On Thu, Jul 2, 2015 at 10:29 PM, Marc Neudert notifications@github.com
wrote:

> Probably the IO device to the logfile had a problem. Could anything have
> happened to the logfile? Like it being deleted and recreated outside of the
> Plug?
> 
> At the moment the file will be recreated if it is not already existing.
> Having a fault inside the IO process of the openened logfile may cause some
> weird behaviour that is not properly handled...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mneudert/plug_accesslog/issues/5#issuecomment-118050488
> .

## 

http://reganmian.net/blog -- Random Stuff that Matters

**Comment by mneudert** [comment]
At the moment the logging is done "in process". Having a more suitable architecture using a GenEvent handler to do the writing is something I already have planned but haven't found the time to actually do it.

**Comment by mneudert** [comment]
I just pushed an update that might fix your problems.

The part that is responsible for writing to the logfiles was extracted to be a monitored event handler. Having a faulty IO device or something like that should not be an issue anymore. And definitely not affect the plug request.

**Comment by houshuang** [comment]
This looks like great work. I put the plug back into production, and so far it's performing great. Don't know what the issue was previously, but anyway very happy that it's working – I was missing the access log!
