### ISSUE TITLE
Graphing

### ISSUE THREAD

**Issue by houshuang** [mneudert/plug_accesslog#6]
This is totally outside the scope of this plug I know, but I just wanted to mention that I'm thinking about writing a little Phoenix module to graph the access_log. Having the log is great, but obviously you'd like to get some insight from it - I had a quick look at awstats and goaccess, but I don't want to install a bunch of php scripts on my server etc. I'm already serving up a bunch of graphic reports from my server using Highcharts, so creating something that does some very simple graphs of number of requests per day, access time etc should be pretty simple... It could even use the formatting string to decode the access_log :) 

One thing I still haven't figured out is how to distribute these kinds of "Phoenix modules". I have written two plugs myself, and they're fairly self-contained, with tests etc. However, this would require at least a controller, template, etc. Not sure how to distribute that in a way that others could just "plug it in" to their own app and get a fully functional "webstats" route.

**Comment by mneudert** [comment]
Hex allows you to define basically whatever files you want to include in your package. And mix allows to have a local dependency with a path definition. Local paths should be suitable to check if Phoenix is happy with such an external module with templates and stuff.

Or you might go the way to have a "self contained phoenix sub-application" delivering your graphs and simply route a path of the application there.

But that is probably something to take over to the phoenix mailing list or stackoverflow as I am just talking out of imagination. And having nested applications might not only be overkill but perhaps even harmful depending on where that path leads to...
