### ISSUE TITLE
Logger in Endpoint

### ISSUE THREAD

**Issue by houshuang** [mneudert/plug_accesslog#7]
Maybe you could mention that it's also possible to put the plug at the top of Endpoint, if people want to capture static requests as well. I tried this and it worked perfectly, but I put it back in routes, since I like to tail -f and see where people go, and it introduced too much noise. However, I still wouldn't mind having some statistics about which static files are served how often etc. Maybe I'll try to log static files to a separate file.

**Comment by mneudert** [comment]
You mean the `Phoenix.Endpoint`, right?

The current docs are targettng a usage based on "pure plugs" without taking any hint at whatever a framework does. However I am with you when it comes to clarifying that usage might vary depending on the framework.

As far as split the logs goes you could always use a `dontlog/1` function. With two plug definitions (one having a negated `dontlog/1` function) your logs should happily be split apart. Or log all the requests not to a file but a separate process just implementing a counter ;)

**Comment by houshuang** [comment]
Exactly, yes I am a bit Phoenix-centric, even though I love the idea of
plugs being generalized. I tried to not depend on any Phoenix libraries in
my own plugs as well.

Thanks for all your ideas and explanations, I really appreciate it.

On Wed, Jul 8, 2015 at 2:40 AM, Marc Neudert notifications@github.com
wrote:

> You mean the Phoenix.Endpoint, right?
> 
> The current docs are targettng a usage based on "pure plugs" without
> taking any hint at whatever a framework does. However I am with you when it
> comes to clarifying that usage might vary depending on the framework.
> 
> As far as split the logs goes you could always use a dontlog/1 function.
> With two plug definitions (one having a negated dontlog/1 function) your
> logs should happily be split apart. Or log all the requests not to a file
> but a separate process just implementing a counter ;)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mneudert/plug_accesslog/issues/7#issuecomment-119297462
> .

## 

http://reganmian.net/blog -- Random Stuff that Matters
